### ISSUE TITLE
Editing Mode

### ISSUE THREAD

**Issue by Aetherinox** [solargate/obsidian-inline-encrypter#2]
I know almost every developer hears this, but unfortunately it is a pain that Obsidian.md has started with Edit / Reading mode having completely different structures to them.

Are their any plans for the "Secret" element being show able in edit mode.

An example would be like with tables:
![lAKizaJDzy](https://github.com/solargate/obsidian-inline-encrypter/assets/118329232/35256790-c064-43b9-bfe6-b700bc57c36d)

In Editing Mode, secrets show up as the clickable interface if you place them inside a table.

However, it would be nice if we could do something similar to the following:
````markdown
```secret
LZZ07NJaNKFjh4Z4kpK7h+mbL16sUZF9fD1QadVAsdWNp3iwNf+c6G6DqhRi/340pnteDjlZswI=
```
````

Once the cursor is moved out of the codeblock, the interface would automatically turn it into 

![image](https://github.com/solargate/obsidian-inline-encrypter/assets/118329232/61d3b4a9-e65e-43ee-a3f9-17ccd08833b5)

Inline doing this in edit mode would be cool too 
![image](https://github.com/solargate/obsidian-inline-encrypter/assets/118329232/f091aa92-290b-4b42-9ee4-f801fcb59176)

Then if they want to actually see the text, put the cursor inside the code and it transforms back into an inline codeblock with text.

I'm in reading mode maybe 5% of the time I'm in obsidian, just because there are a few other plugins that only work there, but most of the time, I'm in editing mode. I wish obsidian would just do something to make the switch seamless on the back-end instead of the structures being so dramatically different.

**Comment by solargate** [comment]
Do you mean editing in live preview mode? Yes, I'll try to implement this.

**Comment by Aetherinox** [comment]
Yeah, I stick to edit mode most of the time.

**Comment by solargate** [comment]
@Aetherinox I released a new version with Live Preview mode support. Please test it. Enjoy! :-)
