### ISSUE TITLE
It doesn't work with Obsidian 1.4.16, under Ubuntu 23.10

### ISSUE THREAD

**Issue by Fastidious** [solargate/obsidian-inline-encrypter#4]
Installed the plugin, and was able to encrypt a code block (the encrypt was on the command palette). After that, nothing shows on the command palette anymore. Nor encrypt, nor decrypt, nothing with "inline" in it. I quit Obsidian, re-opened it, nothing. Disabled plugin, re-enabled it, nothing.

**Comment by solargate** [comment]
@Fastidious Very strange... I use the same version and Ubuntu 23.10 too. Are you sure that you open command pallete in **edit** mode? The commands are avaliable in edit mode only, because it needs to change the content.

Please provide a list of other plugins used. Maybe this is due other plugin...

**Comment by Fastidious** [comment]
@solargate I believe you are correct, my apologies. I was getting confused by toggling read/edit. I just tried it paying attention to what I was doing, and it works fine all the time. Closing the issue. Thanks!
